# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/browen/Documents/COMP-541/Project/Project.cache/wt [current_project]
set_property parent.project_path C:/Users/browen/Documents/COMP-541/Project/Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/browen/Documents/COMP-541/Project/Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab4/display640x480.vh
read_mem {
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/dmem_screentest.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/imem_screentest.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/imem_screentest_nopause.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/imem_etchasketch.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/dmem_etchasketch.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/dmem_full-IO-test.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/bmem_screentest.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/smem_screentest.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Project/imem_full-IO-test.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/new/bmem_test.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/config/bmem.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/config/imem.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/config/dmem.mem
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/config/smem.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/COMP-541/Lab2B/Lab2b.srcs/sources_1/new/ALU.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab5/sources/accelerometer.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/add_sub_8bit.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/adder4bit.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/new/bitmap_mem.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/COMP-541/Project/clockdiv.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/comparator.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/Lab8/controller.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/datapath.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources_1/new/display8digit.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/new/dmem.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/fulladder.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources_1/imports/new/hexto7seg.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/new/imem.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab5/keyboard.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/logical.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/new/memIO.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/Lab8/mips.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/lab6/register_file.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/new/shifter.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/new/signExtend.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/new/smem.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab5/Lab5.srcs/sources_1/imports/Lab5/sound.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/new/vgadisplaydriver.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/new/vgatimer.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/new/xycounter.sv
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/Lab8.srcs/sources_1/imports/Lab8/top.sv
}
read_vhdl -library xil_defaultlib {
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources/ADXL362Ctrl.vhd
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources/AccelArithmetics.vhd
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources/AccelerometerCtl.vhd
  C:/Users/browen/Documents/COMP-541/Project/Project.srcs/sources_1/imports/sources/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/clock.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/clock.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/reset.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/reset.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/vga.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/vga.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/keyboard.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/keyboard.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/accel.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/accel.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/led.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/led.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/segdisplay.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/segdisplay.xdc]

read_xdc C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/sound.xdc
set_property used_in_implementation false [get_files C:/Users/browen/Documents/COMP-541/Project/Project.srcs/constrs_1/imports/Project/sound.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
